define({
  BETA_TAB_LOCATOR: '//*[@href="/beta_tab/"]',
  RESULTS_COUNT_LOCATOR: '#content > div > div:nth-child(2) > section > div.panel-body > div:nth-child(1) > strong',
  FILTER_BTN_LOCATOR: '#content > div > div:nth-child(2) > section > div.panel-heading > div > div.panel-heading > div:nth-child(1) > button',
  USERNAME_INPUT_ID: 'id_username',
  PASSWORD_INPUT_ID: 'id_password',
  LOGIN_BTN_LOCATOR: '#fm-form-login > div > button',
  //LOGIN_BTN_LOCATOR: '//*[@id="fm-form-login"]/div/button',
  PROFILE_LINK_LOCATOR: '#top-bar > *.my_profile > a',
  CREATION_DATE_FILTER_LOCATOR: 'react-select-5--value',
  CHANNEL_FILTER_LOCATOR: 'react-select-6--value',
  GROUP_FILTER_LOCATOR: 'react-select-4--value',
  CONTENT_TAG_FILTER_LOCATOR: 'react-select-7--value',
  LANGUAGE_FILTER_LOCATOR: 'react-select-8--value',
  ATTACHMENT_FILTER_LOCATOR: 'react-select-9--value',
  //DISPLAY_FILTER_LOCATOR: '#search-filters > div > div > div.checkbox-group > div > span > div > svg:nth-child(2) > g > path',
  DISPLAY_FILTER_LOCATOR: '#search-filters > div > div > div.checkbox-group > div > span > svg > g > path',
  MODERATION_FILTER_LOCATOR: 'react-select-10--value',
  TAGGING_FILTER_LOCATOR: 'react-select-11--value',
  RIGHTS_FILTER_LOCATOR: 'react-select-12--value',
  CLEAR_ALL_CHANNELS_LOCATOR: ['#AutoScopeStyle_4 > div > div > span.Select-clear-zone > span', 'css'],
  FACEBOOK_CLEAR_LOCATOR: '#react-select-6--value > div.Select-value > span.Select-value-icon',
  GOOGLEPLUS_CLEAR_LOCATOR: '#react-select-6--value > div.Select-value > span.Select-value-icon',
  INSTAGRAM_CLEAR_LOCATOR: '#react-select-6--value > div.Select-value > span.Select-value-icon',
  TWITTER_CLEAR_LOCATOR: '#react-select-6--value > div.Select-value > span.Select-value-icon',
  YOUTUBE_CLEAR_LOCATOR: '#react-select-6--value > div.Select-value > span.Select-value-icon',
  CLEAR_ALL_LANGUAGES_LOCATOR: ['#AutoScopeStyle_6 > div > div > span.Select-clear-zone > span', 'css'],
  ENGLISH_CLEAR_LOCATOR: '#react-select-8--value > div.Select-value > span.Select-value-icon',
  GERMAN_CLEAR_LOCATOR: '#react-select-8--value > div.Select-value > span.Select-value-icon',
  SPANISH_CLEAR_LOCATOR: '#react-select-8--value > div.Select-value > span.Select-value-icon',
  CLEAR_ALL_TAGS_LOCATOR: ['#AutoScopeStyle_5 > div > div > span.Select-clear-zone > span', 'css'],
  CONTENT_TAG1_CLEAR_LOCATOR: '#react-select-7--value > div.Select-value > span.Select-value-icon',
  CONTENT_TAG2_CLEAR_LOCATOR: '#react-select-7--value > div.Select-value > span.Select-value-icon',
  CONTENT_TAG3_CLEAR_LOCATOR: '#react-select-7--value > div.Select-value > span.Select-value-icon',
  CONTENT_TAG4_CLEAR_LOCATOR: '#react-select-7--value > div.Select-value > span.Select-value-icon',
  CLEAR_ALL_ATTACHMENTS_LOCATOR: ['#AutoScopeStyle_7 > div > div > span.Select-clear-zone > span', 'css'],
  PHOTO_CLEAR_LOCATOR: '#react-select-9--value > div.Select-value > span.Select-value-icon',
  VIDEO_CLEAR_LOCATOR: '#react-select-9--value > div.Select-value > span.Select-value-icon',
  GEOTAG_CLEAR_LOCATOR: '#react-select-9--value > div.Select-value > span.Select-value-icon',
  CLEAR_ALL_MODERATION_LOCATOR: ['#AutoScopeStyle_8 > div > div > span.Select-clear-zone > span', 'css'],
  MOD_QUEUED_CLEAR_LOCATOR: '#react-select-10--value > div.Select-value > span.Select-value-icon',
  MOD_PENDING_CLEAR_LOCATOR: '#react-select-10--value > div.Select-value > span.Select-value-icon',
  MOD_APPROVED_CLEAR_LOCATOR: '#react-select-10--value > div.Select-value > span.Select-value-icon',
  MOD_REJECTED_CLEAR_LOCATOR: '#react-select-10--value > div.Select-value > span.Select-value-icon',
  MOD_OVERRULED_CLEAR_LOCATOR: '#react-select-10--value > div.Select-value > span.Select-value-icon',
  CLEAR_ALL_TAGGING_LOCATOR: ['#AutoScopeStyle_9 > div > div > span.Select-clear-zone > span', 'css'],
  TAGGING_QUEUED_CLEAR_LOCATOR: '#react-select-11--value > div.Select-value > span.Select-value-icon',
  TAGGING_PENDING_CLEAR_LOCATOR: '#react-select-11--value > div.Select-value > span.Select-value-icon',
  TAGGING_COMPLETED_CLEAR_LOCATOR: '#react-select-11--value > div.Select-value > span.Select-value-icon',
  TAGGING_REJECTED_CLEAR_LOCATOR: '#react-select-11--value > div.Select-value > span.Select-value-icon',
  TAGGING_OVERRULED_CLEAR_LOCATOR: '#react-select-11--value > div.Select-value > span.Select-value-icon',
  CLEAR_ALL_RIGHTS_LOCATOR: ['#AutoScopeStyle_10 > div > div > span.Select-clear-zone > span', 'css'],
  RIGHTS_QUEUED_CLEAR_LOCATOR: '#react-select-12--value > div.Select-value > span.Select-value-icon',
  RIGHTS_PENDING_CLEAR_LOCATOR: '#react-select-12--value > div.Select-value > span.Select-value-icon',
  RIGHTS_GRANTED_CLEAR_LOCATOR: '#react-select-12--value > div.Select-value > span.Select-value-icon',
  RIGHTS_DENIED_CLEAR_LOCATOR: '#react-select-12--value > div.Select-value > span.Select-value-icon',
  MODAL_LOCATOR: '//div[@data-reactid=".1.1.0.0"]',
  MODAL_CLOSE_BTN_LOCATOR: '//button[@class="close"]',
  MODAL_NEXT_BTN1_LOCATOR: '//button[@data-reactid=".1.1.0.0.$=11.0.0.1.0"]',
  MODAL_NEXT_BTN2_LOCATOR: '//button[@data-reactid=".1.1.0.0.$=11.0.1.1.0"]',
  MODAL_NAV_RESET_BTN_LOCATOR: '//button[@data-reactid=".1.1.0.0.$=11.0.2.1.0"]',
  MODAL_TEXT1_LOCATOR: '//p[@data-reactid=".1.1.0.0.$=11.0.0.0.1"]',
  MODAL_TEXT2_LOCATOR: '//p[@data-reactid=".1.1.0.0.$=11.0.1.0.1"]',
  MODAL_TEXT3_LOCATOR: '//p[@data-reactid=".1.1.0.0.$=11.0.2.0.1"]',
  UPLOAD_PHOTO_BTN_ID: 'UploadPhoto',
  UPLOAD_PHOTO_BTN_LOCATOR: '//*[@data-reactid=".0.1.1.0.0.0.1.0"]',
  TAKE_A_PHOTO_BTN_LOCATOR: '//*[@data-reactid=".0.1.1.0.0.0.1.1"]',
  UPLOAD_PHOTO_COMMENT_LOCATOR: '//textarea[@data-reactid=".0.1.1.0.0.0.1.0.1"]',
  UPLOAD_VIDEO_COMMENT_LOCATOR: '//textarea[@data-reactid=".0.1.1.0.0.0.1.0.2"]',
  UPLOAD_NICKNAME_LOCATOR: '//input[@data-reactid=".0.1.1.0.0.0.1.0.2"]',
  UPLOAD_VIDEO_NICKNAME_LOCATOR: '//input[@data-reactid=".0.1.1.0.0.0.1.0.3"]',
  UPLOAD_TC_ID: 'check',
  UPLOAD_TC_TEXT: '//*[@data-reactid=".0.1.1.0.0.0.1.1.1"]',
  UPLOAD_SUBMIT_BTN_LOCATOR: '//button[@data-reactid=".0.1.1.0.0.0.1.2"]',
  UPLOAD_VIDEO_BTN_LOCATOR: '//*[@data-reactid=".0.1.1.0.0.0.1.2"]',
  UPLOAD_VIDEO_BTN_LOCATOR2: '//*[@id="app-wrapper"]/div/div[2]/div[2]/div/div/div/form/div/label/input',
  UPLOAD_VIDEO_BTN2_LOCATOR: '//*[@data-reactid=".0.1.1.0.0.0.1.0.0"]',
  UPLOAD_INSTA_BTN_LOCATOR: '//button[@data-reactid=".0.1.1.0.0.0.1.4"]',
  UPLOAD_FB_BTN_LOCATOR: '//button[@data-reactid=".0.1.1.0.0.0.1.3"]',
  INSTA_USERNAME_ID: 'id_username',
  INSTA_PW_ID: 'id_password',
  INSTA_LOGIN_BTN: '#login-form > p.form-actions > input',
  // UPLOAD_INSTA_CONTENT_PHOTO: '//li[@data-reactid=".0.1.1.0.0.0.1.0.$1182265539183991492_1651059053"]',
  UPLOAD_INSTA_CONTENT_PHOTO: '//li[@data-reactid=".0.1.1.0.0.0.1.0.$1241738950658186149_1651059053"]',
  INSTA_LOGIN_LINK_LOCATOR: '//*[@id="react-root"]/section/main/article/div[2]/div[2]/p/a',
  INSTA_USERNAME_LOCATOR: '//*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[1]/input',
  INSTA_PW_LOCATOR: '//*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/div[2]/input',
  INSTA_LOGIN_BTN_LOCATOR: '//*[@id="react-root"]/section/main/article/div[2]/div[1]/div/form/span/button',
  INSTA_PROFILE_LOCATOR: '//a[@data-reactid=".0.2.0.0.1.1.2.0"]',
  FB_EMAIL_LOCATOR: '//*[@id="email"]',
  FB_PASSWORD_LOCATOR: '//*[@id="pass"]',
  FB_LOGIN_BTN_LOCATOR: '//*[@id="loginbutton"]',
  UPLOAD_BACK_BTN: '//*[@data-reactid=".0.1.0.0.0.1"]',
  UPLOAD_THANK_YOU_MESSAGE_LOCATOR: '//*[@data-reactid=".0.1.1.0.0.0.1"]'
});
