define ({
  // General Properties 
  CONSOLE_URL: 'http://fm3.feedmagnet.com',
  BETA_TAB: 'http://fm3.feedmagnet.com/beta_tab/',
  SUBMISSION_URL: 'https://submit-stg.curations.bazaarvoice.com/?client=curations-one&productId=product1&group=pie-test',
  SEARCH_URL: '/?next=/beta_tab/',
  USERNAME: 'incubator_testing1@bazaarvoice.com',
  PASSWORD: 'Password123!',
  COOKIE: [{name: "intro-shown", value: "true", path: "/", domain: "fm3.feedmagnet.com"}],
  FILTER_TIMEOUT: 7000,
  COMBINATION_FILTER_TIMEOUT: 2000,
  DEFAULT_FILTER_RESULTS: '21902',
  // Channel Filter Properties 
  FACEBOOK_FILTER_RESULTS: '133',
  GOOGLEPLUS_FILTER_RESULTS: '15',
  TWITTER_FILTER_RESULTS: '1214',
  INSTAGRAM_FILTER_RESULTS: '19765',
  YOUTUBE_FILTER_RESULTS: '775',
  MULTI_CHANNEL_FILTER_RESULTS: '148',
  // Language Filter Properties 
  LANG_FILTER_RESULTS: '106',
  ENGLISH_FILTER_RESULTS: '16177',
  GERMAN_FILTER_RESULTS: '148',
  SPANISH_FILTER_RESULTS: '579',
  MULTI_LANGUAGE_FILTER_RESULTS: '16325',
  CONTENT_TAG1_FILTER_RESULTS: '3',
  CONTENT_TAG2_FILTER_RESULTS: '2',
  CONTENT_TAG3_FILTER_RESULTS: '2',
  CONTENT_TAG4_FILTER_RESULTS: '1',
  MULTI_CONTENT_TAGS_FILTER_RESULTS: '5',
  PHOTO_FILTER_RESULTS: '20270',
  VIDEO_FILTER_RESULTS: '823',
  GEOTAG_FILTER_RESULTS: '4092',
  MULTI_ATTACHMENTS_FILTER_RESULTS: '21092',
  MOD_QUEUED_FILTER_RESULTS: '3778',
  MOD_PENDING_FILTER_RESULTS: '827',
  MOD_APPROVED_FILTER_RESULTS: '587',
  MOD_REJECTED_FILTER_RESULTS: '14822',
  MOD_OVERRULED_FILTER_RESULTS: '395',
  MULTI_MOD_FILTER_RESULTS: '4605',
  TAGGING_QUEUED_FILTER_RESULTS: '10905',
  TAGGING_PENDING_FILTER_RESULTS: '9679',
  TAGGING_COMPLETED_FILTER_RESULTS: '1318',
  TAGGING_REJECTED_FILTER_RESULTS: '0',
  MULTI_TAGGING_FILTER_RESULTS: '20584',
  RIGHTS_QUEUED_FILTER_RESULTS: '20894',
  RIGHTS_PENDING_FILTER_RESULTS: '45',
  RIGHTS_GRANTED_FILTER_RESULTS: '764',
  RIGHTS_DENIED_FILTER_RESULTS: '199',
  MULTI_RIGHTS_FILTER_RESULTS: '20939',
  COMBINATION1_FILTER_RESULTS: 30,
  COMBINATION2_FILTER_RESULTS: 727,
  FILTER_BTN_TEXT: 'Filter content',
  AS_MODAL_TEXT1: 'Advanced Search is still under development, but we decided to share our progress with you because we want to hear what you think.',
  AS_MODAL_TEXT2: 'View all the content we’ve curated for you in one place. Try out the filters. Don’t worry: it’s just a prototype—you can’t break it.',
  AS_MODAL_TEXT3: 'What should this tool grow up to be? Your feedback and ideas will help us determine what functionality to add.',
  PHOTO_UPLOAD_LOCATION: 'submission/tests/support/files/BV_background_4_1440x900.png',
  VIDEO_UPLOAD_LOCATION: 'submission/tests/support/files/testvid.mp4',
  UPLOAD_THANK_YOU: 'Thank You!',
  UPLOAD_PHOTO_THANK_YOU_MSG: 'Your photo was successfully submitted and is pending approval. Please allow up to 72 hours for your photo to appear on our website.',
  UPLOAD_VIDEO_THANK_YOU_MSG: 'Your video was successfully submitted and is pending approval. Please allow up to 72 hours for your video to appear on our website.',
  INSTA_USERNAME: 'og_instagangsta',
  INSTA_PW: 'h8yst8ck',
  INSTA_URL: 'http://www.instagram.com',
  INSTA_PROFILE_TEXT: 'Profile',
  FACEBOOK_URL: 'https://www.facebook.com',
  FACEBOOK_EMAIL:  'bkjk100@gmail.com',
  FACEBOOK_PW: 'Patriots12$',
  // Mongodb settings   
  MONGO_LOCAL_HOST: 'localhost:27017/qa',
  MONGO_PROD_HOST: 'mongo-prod-fm3.nexus.bazaarvoice.com:27017/qa'
});

